language: java
jdk:
- openjdk8
sudo: false
install: true
group: stable
dist: trusty
os: linux
addons:
  sonarcloud:
    organization: autobake
    branches:
    - ".*"
    token:
      secure: "L5GnDE/fEXjflcW1iqZHdbBZ50Q5B3D3qC8DGxB3eNcTMnqY+bKBsv0T3EYCdtVtEn4MaiXbmLNu2azn8snxtU9jm/Y5/r3yjDjhmTBvndq/bTF3I4OySGI0qw7etCaBTkqKTghkTuJppnqB3UNf1Kik5qfZpwgSAsPpPzlumjlbz6dJ+tKNApbtyZz6oBcn1S2u73Z7v53K7vw844Goee5br0jFOJsKrRF62zuKgGamC0rCxCNyfa5lHbcfQP5t9D+zFwrSAnlATfN/S2mJa74v+YI+2N7VltP6zqqSpnAisKXG3JlYfrkeNMdFjATQejqsiryAOezVAsK+PRCeOBAY6fdHzDFvimdTyJ5KE1ystLx8I8QY/CdqPuIJYHBiRgwxCkSnZfDov1fC0dG72/jv0wWIzXKyRYdyjp83TPchYjLqFRbQAkcfto+MPO8ELKz3Rkz1nAh7dGgUmR8eUW0vSn/4IjCo8ztCC6vO5gRHWPDxerU3WtyxcxmDGBcudT4f2QqWMWLH6nRsiYmOvvfGmmK6TNaROOOSf5a1uITZk8XujF4gME36wE6Bs2Ja3dVkMLE6PJ5CGA2dFEGjmgVgjuPZsoEmIvcmBB9oUysQN/HWIWX1bOv4AIZNEonPluKcKH2NRjn+3QwCd02Y6+YlXait3gbcXa6vcmZea7g="
    github_token:
      secure: "CQi7py+dFXsDJI+CQKhki+VCVLNEiJNz85bLrIz1HX/x2KPRv9MWGDJWjNkwayEgpP9odj6EZB3mC20Wqxpy54d9adEkzLgb8zXtkFXEKtQu79lG5In5Y5AbMPNPtd2OGJINkl2V+VXdko9tj6YfrNrdbkbmuHlpDu6+eac8wnyMZ/ZtZUGnTNgZTVQbT99E5mH7Wx0Y1CO+//co/3Sv3WVNITwZgUJd9TcIYmOThqowggymwojVXPotx6xHJvbdceF0cpFinosgudB4Y/GFL1x40/+JNhOJ0QKfXigvo4Afdx74nVl9N4UH0+1IatJD+VCapJ8vaY3HF0ySEUHNJjZ6hDy9u5gAc0d2hXJV2EAko2pl0KrdQnAfMmZm5itqdfjC7KdC7Ftdu2Z5usSehvmlG3IE0T9+iQpPjVauA3t3xWoCzjuolDagkWmWW8igypGJ44nhm6cgHKKMtYOv5hKLzvSjck82FcTBaJdjjajekOO7yxC80zhEeJ0krO99HzOgvt4qeOGAO8MPSAyhdCdGNT6t4qZ6E19dODvAHeRTZWd8OVCrOE6sBY7pjVe6bCX+zh4tCtp2zCLPn+3Tu/k1iUktQ6uNgqlaGKQ+vo05eiZDhF8FYUSjteb51HESJ7bSsgreut5+35NUXlGQtHjoXYoMOwKFDMX7XwUahDQ="
script:
  - "gradle sonarqube"
