language: java
jdk:
    - openjdk8
sudo: false
install: true
group: stable
dist: trusty
os: linux

addons:
  sonarcloud:
    organization: "autobake"
    branches:
      - ".*"
    token:
      secure: WF1RZM+68RVY8NL2bE8lQhmSGOTf8hG8PDzp6hEavWUnDgaObN0dezoHNX1g0nRK1VFU50q7yr1p5CNZUtGsz0bjvxs1pxo1Qr5ublBLjGLx0pBTx6H/j3ooirgq7rh2s6ZdofjcZkQTXbHPy0rvCkEQ6fvmIsyVNh6ZYTSPxIWI0G8xV7FruxDZE/OnHwDEzP5vRf/tVORuaLhYmCAISF3lRh3m6Cwbt3FyXRVqcvy8mFT6IMGBeC68IcmWDIgYF5aZNviK4lrs7WVT+hVhfOR0puI+1Q+hGUS/m8SYSO+DgtyZ9qCnms+3qILp/njRXjDfVneAOXX8ectVEBWAi7u+BRwrNnGgXVUtrOhHIqG5pKpQzPAVMCK2QoASwzSIl1SR1UCItSjbq7HeDN0+MDUqUcuDddZeXm3wW/OQ/NC0cNxQ8l1Rp0jpm9FHBOY0oX15OMYCdXDSwnFDXu8TKNXoG7D6vS9MpjTDKrjZxwTt1bcXxFW5IbRk4ARo0jT7ZcHD7EOHrshLjcL4BlePlc63Oydu2rO8rTG06CUDPiCSJZIourtDFFCac6S4yh72bT6N599vF4AfGk/mhjNlw6NtHKM1hdzCxcyZXVNNuFmbQuMAuKTCrzUzYZ1upDyZ6N9oSAaXRlCFLL8nwqWWUcvz46wVz9Ln7RHOyMMgfAE= 
    github_token:
      secure: lQfmBkxxL6JvmmD8OqswvyOu8a8t4c1C5Vn4x0MnEdHdQJc/A2ELGkhKXYF8CC7v8kcOY2d2VnZr2GqncpK29Lka28eMNH3xQHTU6D7TGLPsqKHxJfPrqfkFk3BIsPlyE4+ncE7SDmNfsARqST+FM4WfPYl0mlw6wVnLQw3qpAcZdyC6WvpHCWM+mHg3hBbRrb41O5+s8wXG7ctmfXdVf50iDlprm8u8y1AVLTM8DOeY2MQzd8xzPC0bLOsdL1HYdtkVKwJHJACOBNXOO0LH6TMIFJ1GPdAe+6m094dmlXrpQy8RPGfm/v+HlK5qlAYG2MbIFQYolh3VBLF0OHQxVPHV9+GG7mgtrBtsDz4E5y85pCCYGQvmMtjGb8PTBVnPHk/I6bNMaqRYCJiJ5nSSQp6zcRrs+tOLycXgsAgrwKMA5GSX9QjWh4DjCcHFAtX2FwSRe8GkUDOguF1adpkGwe6ZekLBSc+4PfOA7+CEsbBFbqmPi12pq1YEfg3U5AEKXWUF6lHWIocaGz23oPIL0CB/bVLeVtty0UBLOguBL8cX5NruqXDA+hrgLuEmOypsCqVZKYKXTk20yUDFnXY6FDjPsizBpjBuQZ8ygh3Zj1NDsExayL87yBZwTygox8xxbcXpLxZ8R7KXL3mwqJz7DQDpF0vIfJt1TkYgzo1OrjI=
script:
  - "gradle sonarqube"
