language: java
jdk:
- openjdk8
sudo: false
install: true
group: stable
dist: trusty
os: linux
addons:
  sonarcloud:
    organization: autobake
    branches:
    - ".*"
    token:
      secure: "L5GnDE/fEXjflcW1iqZHdbBZ50Q5B3D3qC8DGxB3eNcTMnqY+bKBsv0T3EYCdtVtEn4MaiXbmLNu2azn8snxtU9jm/Y5/r3yjDjhmTBvndq/bTF3I4OySGI0qw7etCaBTkqKTghkTuJppnqB3UNf1Kik5qfZpwgSAsPpPzlumjlbz6dJ+tKNApbtyZz6oBcn1S2u73Z7v53K7vw844Goee5br0jFOJsKrRF62zuKgGamC0rCxCNyfa5lHbcfQP5t9D+zFwrSAnlATfN/S2mJa74v+YI+2N7VltP6zqqSpnAisKXG3JlYfrkeNMdFjATQejqsiryAOezVAsK+PRCeOBAY6fdHzDFvimdTyJ5KE1ystLx8I8QY/CdqPuIJYHBiRgwxCkSnZfDov1fC0dG72/jv0wWIzXKyRYdyjp83TPchYjLqFRbQAkcfto+MPO8ELKz3Rkz1nAh7dGgUmR8eUW0vSn/4IjCo8ztCC6vO5gRHWPDxerU3WtyxcxmDGBcudT4f2QqWMWLH6nRsiYmOvvfGmmK6TNaROOOSf5a1uITZk8XujF4gME36wE6Bs2Ja3dVkMLE6PJ5CGA2dFEGjmgVgjuPZsoEmIvcmBB9oUysQN/HWIWX1bOv4AIZNEonPluKcKH2NRjn+3QwCd02Y6+YlXait3gbcXa6vcmZea7g="
    github_token:
      secure: "J9U0bCp/hQ3tWIWKDxNKPfU/q/StwZhiNMySnl36HMv4TzZJxOHw1va/UgFerX28PEBpso+8+86nQYDzytSKsJJ/8ix98rXbIATzUvEXHwjc9GE/sOvE/0B82d/88bC7lHpzvMDqcrk0Xx/fY4JaHLnxp4h8AXPhGGyVQbVnQ4zdVzBedb/a4tGHuNr6oW6luUi0i+6eBqVQyWs1cA1uGtDjkgBU3fab3ziE37fAkjc+quetqcntjErcKKMdPjYJj3mR/NwOQMkfcZX4+lOdsw98KlMJXsK/k/WPq6f+xeGPADBOVXhDZxXqywVAQqufuwXVuO1y8hCzphuf5NT03ZzM9AHhiJg8u8IQKEmMDmQX8ComxYKB2TbeVAbj5Xcqn543eJuf/M+QEy9vmtqbbl7tAeb7o01OEbvrzjAIpG+JQXd4G4VxYKQuHHNhsQoA54uInQu2y8NTumQX0Grr2HIYAI9IAo58v2nbxIoAcutt3/7JqX+GHxYfYdqHSWP9vmwzyyLysSULPFWZXtgi4yxw5vMT5tz9hqKXUxz2yXK0h4Ixx3QaOBW1jALXpHLga2hNyMhcWxUjkVRxKWVD3MZbgmFxPspPFxOEHJRCZseDxCvz9MXN02HGRu0PbXR5qW9LyAWgXcLjJupvBbAekL2EKQbx1HbQsUbu+MsQUQI="
script:
  - "gradle sonarqube"
